# -*- coding: utf-8 -*-
"""Sub-CPMK data for 043 docs — Core STI Semester 6 & 7."""
SUBCPMK_S67 = {
"STI-624": [
 ("1.1", "Mengonversi model Machine Learning/Deep Learning ke format ONNX/TensorRT.", "1", "C4"),
 ("1.2", "Mengemas model ke kontainer untuk layanan inferensi.", "1", "C4"),
 ("2.1", "Membangun RESTful/gRPC inference service yang dapat diintegrasikan ke sistem.", "2", "C6"),
 ("2.2", "Mengimplementasikan Retrieval-Augmented Generation (RAG) dengan vector database.", "2", "C6"),
 ("3.1", "Mengintegrasikan layanan AI ke platform digital yang ada.", "3", "C6"),
 ("3.2", "Mengelola keamanan dan autentikasi layanan inferensi AI.", "3", "C5"),
 ("4.1", "Melakukan load testing untuk mengukur kapasitas layanan AI.", "4", "C5"),
 ("4.2", "Menyusun strategi monitoring latensi dan kesehatan layanan rekomendasi/model.", "4", "C5"),
],
"STI-625": [
 ("1.1", "Merancang arsitektur layanan Smart City sesuai kerangka SPBE (Perpres).", "1", "C4"),
 ("1.2", "Menganalisis komponen smart city (transportasi, energi, keamanan, lingkungan).", "1", "C4"),
 ("2.1", "Membangun aplikasi Web GIS menggunakan Leaflet/Mapbox untuk visualisasi spasial.", "2", "C6"),
 ("2.2", "Mengintegrasikan data telemetri perkotaan ke platform layanan.", "2", "C6"),
 ("3.1", "Menganalisis interoperabilitas data pada kerangka Satu Data Indonesia.", "3", "C4"),
 ("3.2", "Merancang integrasi data lintas instansi pemerintahan digital.", "3", "C4"),
 ("4.1", "Menyusun masterplan smart city berbasis kebutuhan dan kapasitas kota.", "4", "C6"),
 ("4.2", "Membangun purwarupa layanan smart city end-to-end yang terintegrasi data.", "4", "C6"),
],
"STI-626": [
 ("1.1", "Menerapkan prinsip MLP dan backpropagation pada neural network.", "1", "C3"),
 ("1.2", "Mengimplementasikan training jaringan saraf tiruan menggunakan PyTorch/TensorFlow.", "1", "C3"),
 ("2.1", "Mengonstruksi model CNN (ResNet, VGG) untuk klasifikasi citra.", "2", "C5"),
 ("2.2", "Menerapkan transfer learning dan object detection (YOLO) pada data visual.", "2", "C5"),
 ("3.1", "Mengonstruksi model RNN/LSTM/GRU untuk data sekuensial.", "3", "C5"),
 ("3.2", "Menerapkan mekanisme Transformer self-attention pada pemrosesan sekuens.", "3", "C5"),
 ("4.1", "Menerapkan regularisasi (dropout, batch norm) dan teknik optimasi pada pelatihan model.", "4", "C6"),
 ("4.2", "Mengevaluasi dan menyempurnakan performa model deep learning pada dataset nyata.", "4", "C6"),
],
"STI-627": [
 ("1.1", "Merancang arsitektur microservices berbasis Domain-Driven Design (DDD).", "1", "C4"),
 ("1.2", "Menerapkan pola event-driven dan message broker (Kafka/RabbitMQ).", "1", "C4"),
 ("2.1", "Mengimplementasikan API Gateway dan circuit breaker pada layanan platform.", "2", "C3"),
 ("2.2", "Menerapkan pola Saga untuk transaksi terdistribusi antar microservices.", "2", "C3"),
 ("3.1", "Mengontainerisasi layanan dan menyusun pipeline CI/CD.", "3", "C4"),
 ("3.2", "Mengonfigurasi observability (logging, tracing, metrik) pada platform.", "3", "C4"),
 ("4.1", "Membangun platform digital terintegrasi berbasis arsitektur layanan modern.", "4", "C6"),
 ("4.2", "Mengevaluasi keandalan dan skalabilitas platform digital yang dibangun.", "4", "C6"),
],
"STI-728": [
 ("1.1", "Menganalisis problem-solution fit dengan pendekatan Lean Startup.", "1", "C4"),
 ("1.2", "Menyusun value proposition dan identifikasi segmen pasar sasaran.", "1", "C4"),
 ("2.1", "Membangun Minimum Viable Product (MVP) fungsional dari ide startup.", "2", "C6"),
 ("2.2", "Menguji MVP kepada pengguna awal dan mengiterasi berdasarkan umpan balik.", "2", "C6"),
 ("3.1", "Menganalisis metrik pertumbuhan startup (AARRR, CAC, LTV, Burn Rate).", "3", "C4"),
 ("3.2", "Menyusun strategi pertumbuhan dan monetisasi startup digital.", "3", "C4"),
 ("4.1", "Menyusun investor pitch deck dan rencana bisnis startup.", "4", "C6"),
 ("4.2", "Mempresentasikan startup pada ajang Demo Day dengan argumen bisnis yang valid.", "4", "C6"),
],
}
