# -*- coding: utf-8 -*-
"""Sub-CPMK data for 043 docs — Core STI Semester 2 & 3."""
SUBCPMK_S23 = {
"STI-204": [
 ("1.1", "Membuktikan validitas argumen logika proposisi melalui tabel kebenaran dan hukum aljabar logika.", "1", "C3"),
 ("1.2", "Menerapkan inferensi logika predikat dan induksi matematika untuk memverifikasi kebenaran algoritma.", "1", "C3"),
 ("2.1", "Menerapkan relasi ekuivalensi dan himpunan terurut parsial (Poset) pada pemodelan struktur data.", "2", "C3"),
 ("2.2", "Menerapkan aljabar Boolean dan kombinatorika pada logika query basis data.", "2", "C3"),
 ("3.1", "Menganalisis struktur graf menggunakan matriks representasi (Adjacency Matrix) dan penelusuran lintasan.", "3", "C4"),
 ("3.2", "Menerapkan pohon (tree) untuk optimasi lintasan pada jaringan data/komputer.", "3", "C4"),
 ("4.1", "Mengonstruksi model DFA untuk pengenalan pola bahasa formal.", "4", "C4"),
 ("4.2", "Mengonstruksi model NFA dan konversinya ke DFA untuk transisi status sistem komputasi.", "4", "C4"),
],
"STI-205": [
 ("1.1", "Menyelesaikan Sistem Persamaan Linear (SPL) menggunakan eliminasi Gauss-Jordan dan matriks invers.", "1", "C3"),
 ("1.2", "Menentukan jenis solusi SPL (tunggal, tak hingga, atau tak ada) dari bentuk eselon baris.", "1", "C3"),
 ("2.1", "Menganalisis kombinasi linier, kebebasan linier, dan rentang (span) pada ruang vektor.", "2", "C4"),
 ("2.2", "Menentukan basis dan dimensi ruang vektor R^n.", "2", "C4"),
 ("3.1", "Menghitung nilai eigen, vektor eigen, dan diagonalisasi matriks.", "3", "C3"),
 ("3.2", "Menerapkan diagonalisasi matriks pada transformasi linier.", "3", "C3"),
 ("4.1", "Merumuskan dekomposisi SVD (Singular Value Decomposition) suatu matriks.", "4", "C4"),
 ("4.2", "Menerapkan PCA (NumPy) untuk reduksi dimensi pada pemrosesan data AI.", "4", "C4"),
],
"STI-306": [
 ("1.1", "Mengelisitasi kebutuhan fungsional dan non-fungsional dari pemangku kepentingan.", "1", "C4"),
 ("1.2", "Menyusun dokumen spesifikasi kebutuhan sistem (SRS) sesuai standar IEEE 830.", "1", "C4"),
 ("2.1", "Memodelkan alur proses bisnis dengan notasi BPMN 2.0.", "2", "C4"),
 ("2.2", "Menganalisis efisiensi proses As-Is vs To-Be pada rantai proses bisnis organisasi.", "2", "C4"),
 ("3.1", "Merancang pemodelan fungsional UML (Use Case dan Activity) secara konsisten.", "3", "C4"),
 ("3.2", "Merancang pemodelan struktural UML (Class, Sequence, State Machine) secara konsisten.", "3", "C4"),
 ("4.1", "Menyusun dokumen arsitektur perangkat lunak (SDD) yang siap diimplementasikan.", "4", "C5"),
 ("4.2", "Menyusun rencana desain perangkat lunak yang selaras dengan kebutuhan bisnis.", "4", "C5"),
],
"STI-307": [
 ("1.1", "Menerapkan algoritma pencarian heuristik A* dan Greedy Best-First pada optimasi ruang status.", "1", "C3"),
 ("1.2", "Menerapkan algoritma Minimax pada permasalahan pengambilan keputusan bercabang.", "1", "C3"),
 ("2.1", "Merancang sistem pakar dengan penalaran Forward Chaining berbasis basis aturan.", "2", "C4"),
 ("2.2", "Merancang sistem pakar dengan penalaran Backward Chaining secara logis dan konsisten.", "2", "C4"),
 ("3.1", "Mengimplementasikan sistem inferensi logika fuzzy metode Mamdani untuk pengambilan keputusan.", "3", "C4"),
 ("3.2", "Mengimplementasikan sistem inferensi logika fuzzy metode Sugeno untuk pengambilan keputusan.", "3", "C4"),
],
"STI-308": [
 ("1.1", "Melakukan riset pengguna (user research) melalui wawancara, observasi, dan persona.", "1", "C4"),
 ("1.2", "Menerapkan metodologi Design Thinking pada proses perancangan antarmuka.", "1", "C4"),
 ("2.1", "Merancang arsitektur informasi dan alur pengguna (user flow) pada aplikasi web/mobile.", "2", "C4"),
 ("2.2", "Membangun wireframe low-fidelity yang terstruktur berdasarkan arsitektur informasi.", "2", "C4"),
 ("3.1", "Membangun prototype high-fidelity interaktif dan design system menggunakan Figma.", "3", "C6"),
 ("3.2", "Menerapkan kepatuhan standar aksesibilitas WCAG pada desain antarmuka.", "3", "C6"),
 ("4.1", "Mengevaluasi kegunaan antarmuka menggunakan System Usability Scale (SUS).", "4", "C5"),
 ("4.2", "Mengevaluasi kegunaan antarmuka menggunakan Heuristic Evaluation dengan analisis kualitatif.", "4", "C5"),
],
"STI-309": [
 ("1.1", "Memilih model proses pengembangan perangkat lunak (Waterfall, V-Model, Scrum, Kanban) yang tepat.", "1", "C4"),
 ("1.2", "Membandingkan karakteristik model proses pengembangan untuk proyek industri.", "1", "C4"),
 ("2.1", "Menerapkan arsitektur perangkat lunak modular dan prinsip SOLID dengan coupling rendah.", "2", "C3"),
 ("2.2", "Menerapkan design pattern (GoF) pada perancangan subsistem perangkat lunak.", "2", "C3"),
 ("3.1", "Merancang skenario pengujian White-Box (basis path, cyclomatic complexity).", "3", "C4"),
 ("3.2", "Merancang skenario pengujian Black-Box (BVA, equivalence partitioning) berdasarkan spesifikasi.", "3", "C4"),
 ("4.1", "Mengevaluasi kualitas perangkat lunak berdasarkan standar ISO/IEC 25010.", "4", "C5"),
 ("4.2", "Mengevaluasi hasil pengujian unit dan integrasi secara otomatis dan objektif.", "4", "C5"),
],
"STI-310": [
 ("1.1", "Menganalisis siklus hidup proses dan mekanisme thread pada sistem multitasking.", "1", "C4"),
 ("1.2", "Menganalisis algoritma penjadwalan CPU (FCFS, SJF, Round Robin, Priority) dengan rata-rata waktu tunggu.", "1", "C4"),
 ("2.1", "Menyelesaikan permasalahan sinkronisasi proses (race condition) menggunakan Semaphore dan Mutex.", "2", "C3"),
 ("2.2", "Menyelesaikan permasalahan deadlock menggunakan Algoritma Banker secara matematis.", "2", "C3"),
 ("3.1", "Mengevaluasi kinerja manajemen memori virtual (paging, segmentasi, page replacement).", "3", "C5"),
 ("3.2", "Mengevaluasi alokasi sistem berkas (file system) pada arsitektur sistem operasi modern.", "3", "C5"),
],
"STI-311": [
 ("1.1", "Membangun struktur halaman web responsif menggunakan HTML5 semantik.", "1", "C3"),
 ("1.2", "Mengimplementasikan tata letak responsif menggunakan CSS3 Flexbox, Grid, dan variabel CSS.", "1", "C3"),
 ("2.1", "Mengimplementasikan interaktivitas client-side menggunakan JavaScript ES6+ (DOM, Async/Await).", "2", "C3"),
 ("2.2", "Mengelola state dan komunikasi data menggunakan Fetch API secara modular.", "2", "C3"),
 ("3.1", "Membangun Single Page Application berbasis komponen menggunakan React (Hooks, Context API).", "3", "C6"),
 ("3.2", "Mengimplementasikan routing antar halaman pada aplikasi SPA.", "3", "C6"),
 ("4.1", "Mengintegrasikan front-end dengan RESTful API eksternal.", "4", "C5"),
 ("4.2", "Mengoptimalkan performa loading aplikasi dengan skor Google Lighthouse minimal 85.", "4", "C5"),
],
"STI-312": [
 ("1.1", "Merancang skema pengalamatan IPv4 menggunakan teknik VLSM dan CIDR.", "1", "C4"),
 ("1.2", "Menerapkan pengalamatan IPv6 pada perancangan jaringan.", "1", "C4"),
 ("2.1", "Mengonfigurasi perangkat Switch dan Router untuk implementasi VLAN dan Trunking.", "2", "C3"),
 ("2.2", "Mengimplementasikan Inter-VLAN Routing pada topologi jaringan kampus.", "2", "C3"),
 ("3.1", "Mengimplementasikan protokol routing dinamis OSPF pada topologi multi-router.", "3", "C3"),
 ("3.2", "Menganalisis protokol lapisan aplikasi (HTTP, DNS, DHCP) menggunakan Wireshark.", "3", "C4"),
 ("4.1", "Menganalisis keamanan Access Control List (ACL) dasar pada lalu lintas jaringan.", "4", "C4"),
 ("4.2", "Mengevaluasi kinerja layanan jaringan (DNS, DHCP, NAT) pada rancangan jaringan.", "4", "C4"),
],
}
