# -*- coding: utf-8 -*-
"""Sub-CPMK data for 043 docs — MK Peminatan Semester 5 & 6."""
SUBCPMK_P56 = {
"STA-501": [
 ("1.1", "Mengimplementasikan metode pengambilan keputusan multikriteria SAW dan WP.", "1", "C3"),
 ("1.2", "Mengimplementasikan metode AHP dan TOPSIS beserta uji konsistensi (CR).", "1", "C3"),
 ("2.1", "Menerapkan metode PROMETHEE dan Fuzzy AHP pada perankingan alternatif.", "2", "C4"),
 ("2.2", "Menganalisis hasil keputusan multikriteria melalui analisis sensitivitas.", "2", "C4"),
 ("3.1", "Membangun aplikasi web DSS interaktif untuk pengambilan keputusan.", "3", "C6"),
 ("3.2", "Mengevaluasi keandalan sistem pendukung keputusan yang dibangun.", "3", "C6"),
],
"STB-501": [
 ("1.1", "Mengonfigurasi Intrusion Detection/Prevention System (Snort/Suricata).", "1", "C4"),
 ("1.2", "Menganalisis lalu lintas PCAP menggunakan Wireshark dan Zeek.", "1", "C4"),
 ("2.1", "Melakukan akuisisi bukti digital (bit-stream image) sesuai standar forensik.", "2", "C4"),
 ("2.2", "Menganalisis forensik memori/disk menggunakan Autopsy dan Volatility.", "2", "C4"),
 ("3.1", "Menyusun chain of custody dan laporan investigasi digital forensik.", "3", "C5"),
 ("3.2", "Mengevaluasi temuan forensik untuk rekomendasi peningkatan keamanan jaringan.", "3", "C5"),
],
"STC-501": [
 ("1.1", "Menerapkan metodologi UX Research (in-depth interview, contextual inquiry) untuk memahami pengguna.", "1", "C4"),
 ("1.2", "Membangun persona dan customer journey map (CJM) berdasarkan data riset.", "1", "C4"),
 ("2.1", "Mengkuantifikasi usability menggunakan SUS dan NPS.", "2", "C4"),
 ("2.2", "Menganalisis hasil pengukuran usability untuk perbaikan desain.", "2", "C4"),
 ("3.1", "Merancang enterprise design system yang konsisten dan dapat diskalakan.", "3", "C6"),
 ("3.2", "Menerapkan kepatuhan aksesibilitas WCAG pada hasil desain riset.", "3", "C6"),
],
"STA-601": [
 ("1.1", "Menganalisis representasi floating-point IEEE 754 dan sumber galat numerik.", "1", "C4"),
 ("1.2", "Mengevaluasi kestabilan dan konvergensi perhitungan numerik.", "1", "C4"),
 ("2.1", "Mengimplementasikan metode pencarian akar non-linier Newton-Raphson dan Secant.", "2", "C3"),
 ("2.2", "Menerapkan interpolasi Spline dan solusi numerik SPL.", "2", "C3"),
 ("3.1", "Mengimplementasikan integrasi numerik Romberg/Gauss-Legendre.", "3", "C4"),
 ("3.2", "Menerapkan metode numerik PDB (RK4) untuk masalah komputasi.", "3", "C4"),
 ("4.1", "Menerapkan optimasi SGD/Gradient Descent pada masalah komputasi numerik.", "4", "C6"),
 ("4.2", "Membangun solusi komputasi numerik end-to-end dengan Python/NumPy.", "4", "C6"),
],
"STA-602": [
 ("1.1", "Merancang arsitektur agen cerdas berbasis model Belief-Desire-Intention (BDI).", "1", "C4"),
 ("1.2", "Menganalisis peran dan interaksi antar agen pada Multi-Agent System (MAS).", "1", "C4"),
 ("2.1", "Mengimplementasikan komunikasi agen menggunakan protokol FIPA-ACL.", "2", "C6"),
 ("2.2", "Membangun simulasi agen menggunakan framework Mesa/JADE.", "2", "C6"),
 ("3.1", "Menerapkan mekanisme negosiasi dan koordinasi antar agen.", "3", "C4"),
 ("3.2", "Menerapkan reinforcement learning dasar pada perilaku agen.", "3", "C4"),
 ("4.1", "Membangun sistem multi-agen untuk menyelesaikan masalah terdistribusi.", "4", "C5"),
 ("4.2", "Mengevaluasi kinerja dan efektivitas sistem agen yang dibangun.", "4", "C5"),
],
"STB-601": [
 ("1.1", "Mengelola infrastruktur cloud sebagai kode menggunakan Terraform (IaC).", "1", "C4"),
 ("1.2", "Menganalisis konsep orkestrasi Kubernetes (Deployments, StatefulSets, Ingress, PV).", "1", "C4"),
 ("2.1", "Mengelola paket aplikasi dan rilis menggunakan Helm.", "2", "C4"),
 ("2.2", "Menerapkan GitOps (ArgoCD) untuk deployment berkelanjutan.", "2", "C4"),
 ("3.1", "Menyusun pipeline CI/CD kontainer untuk otomasi rilis aplikasi.", "3", "C6"),
 ("3.2", "Mengevaluasi keandalan dan keamanan jalur deployment DevOps.", "3", "C6"),
],
"STB-602": [
 ("1.1", "Menganalisis proses penilaian risiko kualitatif dan kuantitatif (SLE, ARO, ALE).", "1", "C4"),
 ("1.2", "Menerapkan pendekatan ISO/IEC 27005 dan NIST SP 800-30 pada penilaian risiko.", "1", "C4"),
 ("2.1", "Menyusun Risk Treatment Plan untuk memitigasi risiko keamanan.", "2", "C4"),
 ("2.2", "Menerapkan analisis dampak bisnis (BIA) pada aset kritis organisasi.", "2", "C4"),
 ("3.1", "Menyusun rencana kelangsungan bisnis (BCP) dan pemulihan bencana (DRP).", "3", "C5"),
 ("3.2", "Mengevaluasi efektivitas program manajemen risiko keamanan informasi.", "3", "C5"),
],
"STC-601": [
 ("1.1", "Memodelkan proses bisnis lanjutan menggunakan BPMN 2.0.", "1", "C4"),
 ("1.2", "Menganalisis peluang otomasi pada proses bisnis organisasi.", "1", "C4"),
 ("2.1", "Mengimplementasikan otomasi proses bisnis menggunakan RPA (UiPath).", "2", "C6"),
 ("2.2", "Memodelkan dan mengeksekusi BPM menggunakan engine Camunda.", "2", "C6"),
 ("3.1", "Mengintegrasikan sistem melalui ESB/API dan middleware.", "3", "C6"),
 ("3.2", "Membangun solusi Business Process Automation end-to-end.", "3", "C6"),
],
"STC-602": [
 ("1.1", "Menganalisis kebutuhan dan alur transaksi aplikasi FinTech (e-wallet, AML/risk rule).", "1", "C4"),
 ("1.2", "Menganalisis kebutuhan aplikasi EdTech (LMS, SIS, proctoring).", "1", "C4"),
 ("2.1", "Mengintegrasikan payment gateway pada aplikasi FinTech.", "2", "C4"),
 ("2.2", "Merancang alur pembayaran dan pencatatan transaksi yang aman.", "2", "C4"),
 ("3.1", "Membangun aplikasi industri vertikal (FinTech/EdTech) yang siap pakai.", "3", "C6"),
 ("3.2", "Mengevaluasi kepatuhan dan keamanan aplikasi industri vertikal.", "3", "C6"),
],
}
