# -*- coding: utf-8 -*-
"""Sub-CPMK data for 043 docs — MK Peminatan Semester 7."""
SUBCPMK_P7 = {
"STA-701": [
 ("1.1", "Menganalisis siklus hidup MLOps (CI/CD/CT) untuk model Machine Learning.", "1", "C4"),
 ("1.2", "Mengelola eksperimen dan registry model menggunakan MLflow.", "1", "C4"),
 ("2.1", "Mengotomasi retraining model dan monitoring data drift.", "2", "C6"),
 ("2.2", "Menerapkan feature store untuk konsistensi data model.", "2", "C6"),
 ("3.1", "Mendeploy model dengan strategi canary dan blue-green.", "3", "C5"),
 ("3.2", "Mengevaluasi performa dan stabilitas pipeline AI di produksi.", "3", "C5"),
],
"STA-702": [
 ("1.1", "Menerapkan fine-tuning model LLM/Transformer untuk kebutuhan spesifik.", "1", "C3"),
 ("1.2", "Menyusun prompt engineering yang efektif untuk tugas percakapan.", "1", "C3"),
 ("2.1", "Membangun sistem RAG menggunakan LangChain dan vector database.", "2", "C6"),
 ("2.2", "Mengimplementasikan agentic AI dengan tool-use dan pemanggilan fungsi.", "2", "C6"),
 ("3.1", "Mengevaluasi kualitas respons percakapan asisten AI.", "3", "C4"),
 ("3.2", "Mengintegrasikan asisten percakapan ke saluran layanan pengguna.", "3", "C4"),
 ("4.1", "Membangun intelligent assistant end-to-end yang andal.", "4", "C6"),
 ("4.2", "Menyempurnakan perilaku asisten berdasarkan evaluasi pengguna.", "4", "C6"),
],
"STA-703": [
 ("1.1", "Menerapkan video analytics dan deteksi objek real-time (YOLO) pada edge device.", "1", "C4"),
 ("1.2", "Menganalisis alur pengolahan citra dan pelacakan objek/re-identification.", "1", "C4"),
 ("2.1", "Mengintegrasikan kamera dan sensor untuk akuisisi data pengawasan.", "2", "C4"),
 ("2.2", "Mengirim data telemetri dari edge ke platform secara real-time.", "2", "C4"),
 ("3.1", "Membangun dashboard monitoring IoT untuk visualisasi analitik.", "3", "C6"),
 ("3.2", "Mengembangkan pipeline analitik smart surveillance end-to-end.", "3", "C6"),
 ("4.1", "Mengevaluasi keandalan dan latensi sistem smart surveillance.", "4", "C6"),
 ("4.2", "Menyempurnakan sistem pengawasan berdasarkan metrik akurasi deteksi.", "4", "C6"),
],
"STB-701": [
 ("1.1", "Menganalisis domain tata kelola TI COBIT 2019 (EDM, APO, BAI, DSS, MEA).", "1", "C4"),
 ("1.2", "Menerapkan prinsip tata kelola COBIT 2019 pada organisasi.", "1", "C4"),
 ("2.1", "Memetakan tujuan TI dan tujuan perusahaan menggunakan model COBIT 2019.", "2", "C4"),
 ("2.2", "Menyusun metrik kinerja tata kelola pada kuadran strategis CMMI.", "2", "C4"),
 ("3.1", "Menyusun rekomendasi perbaikan tata kelola TI berdasarkan hasil audit.", "3", "C5"),
 ("3.2", "Mengevaluasi keselarasan tata kelola TI dengan strategi organisasi.", "3", "C5"),
],
"STB-702": [
 ("1.1", "Menjelaskan Service Value System dan praktik ITIL 4 (Core, Improve, Drive).", "1", "C2"),
 ("1.2", "Menjelaskan peran SLA/OLA pada pengelolaan layanan TI.", "1", "C2"),
 ("2.1", "Mengimplementasikan manajemen incident dan problem pada organisasi.", "2", "C4"),
 ("2.2", "Menerapkan manajemen change dan release management.", "2", "C4"),
 ("3.1", "Mengevaluasi efektivitas service desk dan proses layanan ITIL 4.", "3", "C5"),
 ("3.2", "Menyusun rekomendasi perbaikan layanan TI berdasarkan metrik ITIL.", "3", "C5"),
],
"STB-703": [
 ("1.1", "Menjelaskan pendekatan TOGAF ADM (Architecture Vision hingga Migration Planning).", "1", "C2"),
 ("1.2", "Menjelaskan peran model arsitektur enterprise pada organisasi.", "1", "C2"),
 ("2.1", "Memodelkan arsitektur business dan data menggunakan ArchiMate.", "2", "C4"),
 ("2.2", "Memodelkan arsitektur application dan technology menggunakan ArchiMate.", "2", "C4"),
 ("3.1", "Menyusun dokumen enterprise architecture yang selaras strategi organisasi.", "3", "C5"),
 ("3.2", "Mengevaluasi kesenjangan arsitektur (gap analysis) dan rencana migrasi.", "3", "C5"),
],
"STC-701": [
 ("1.1", "Menerapkan teknologi XR (AR, VR, MR) pada aplikasi imersif.", "1", "C3"),
 ("1.2", "Membuat dan mengelola 3D asset menggunakan WebGL/Three.js.", "1", "C3"),
 ("2.1", "Mengimplementasikan interaksi kontroller dan gestur spasial.", "2", "C6"),
 ("2.2", "Mengintegrasikan Computer Vision/AI untuk pengalaman imersif.", "2", "C6"),
 ("3.1", "Membangun aplikasi immersive/XR end-to-end yang dapat dijalankan.", "3", "C6"),
 ("3.2", "Mengevaluasi kualitas dan performa pengalaman imersif.", "3", "C6"),
],
"STC-702": [
 ("1.1", "Merancang arsitektur SaaS multi-tenant dengan isolasi antar tenant.", "1", "C4"),
 ("1.2", "Menganalisis skema sharing database pada arsitektur multi-tenant.", "1", "C4"),
 ("2.1", "Mengimplementasikan proses on-boarding tenant dan manajemen kuota.", "2", "C6"),
 ("2.2", "Menerapkan mekanisme monetisasi dan metering (plan, quota) pada SaaS.", "2", "C6"),
 ("3.1", "Membangun aplikasi SaaS dengan arsitektur multi-tenant yang andal.", "3", "C4"),
 ("3.2", "Mengevaluasi skalabilitas dan keamanan isolasi antar tenant.", "3", "C4"),
],
"STC-703": [
 ("1.1", "Menyusun product vision dan OKR produk digital.", "1", "C4"),
 ("1.2", "Melakukan product discovery untuk memahami kebutuhan pengguna.", "1", "C4"),
 ("2.1", "Menerapkan prioritisasi fitur menggunakan metode RICE dan Kano.", "2", "C4"),
 ("2.2", "Menyusun PRD dengan user stories dan acceptance criteria.", "2", "C4"),
 ("3.1", "Menerapkan agile product management pada siklus pengembangan produk.", "3", "C6"),
 ("3.2", "Mengevaluasi metrik produk (activation, retention, revenue) untuk perbaikan.", "3", "C6"),
],
}
