# -*- coding: utf-8 -*-
"""Sub-CPMK data for 043 docs — Core STI Semester 4 & 5."""
SUBCPMK_S45 = {
"STI-413": [
 ("1.1", "Menerapkan alur kerja rekayasa data ML (EDA, imputation, encoding, scaling) menggunakan scikit-learn.", "1", "C3"),
 ("1.2", "Menyusun pipeline Machine Learning yang bebas data leakage.", "1", "C3"),
 ("2.1", "Mengonstruksi dan melatih model supervised (Linear/Logistic Regression, Decision Tree, Random Forest, SVM).", "2", "C5"),
 ("2.2", "Mengonstruksi model unsupervised (K-Means, Hierarchical, PCA) untuk segmentasi dan reduksi dimensi.", "2", "C5"),
 ("3.1", "Mengevaluasi performa model menggunakan Confusion Matrix, F1-Score, dan ROC-AUC.", "3", "C5"),
 ("3.2", "Membangun purwarupa inferensi model terintegrasi dengan data baru.", "3", "C6"),
],
"STI-414": [
 ("1.1", "Menerapkan tahapan text preprocessing (tokenisasi, normalisasi, stopword, stemming/lemmatisasi).", "1", "C3"),
 ("1.2", "Membangun representasi teks Vector Space Model (VSM) dan TF-IDF pada korpus.", "1", "C3"),
 ("2.1", "Mengimplementasikan Information Retrieval dengan BM25 dan inverted index.", "2", "C4"),
 ("2.2", "Mengevaluasi kinerja IR menggunakan metrik presisi, recall, dan F1.", "2", "C4"),
 ("3.1", "Mengimplementasikan word embedding dasar (Word2Vec) untuk representasi teks.", "3", "C4"),
 ("3.2", "Mengembangkan model klasifikasi teks dan analisis sentimen (Naive Bayes, SVM teks) dengan F1 optimal.", "3", "C4"),
 ("4.1", "Merancang purwarupa aplikasi NLP/mesin pencari menggunakan library modern (spaCy/NLTK/HuggingFace).", "4", "C5"),
 ("4.2", "Mengintegrasikan API/library NLP modern sebagai solusi cerdas kebutuhan pengguna.", "4", "C5"),
],
"STI-415": [
 ("1.1", "Merancang skema multidimensi data warehouse (Star Schema dan Snowflake Schema).", "1", "C4"),
 ("1.2", "Menerapkan penanganan Slowly Changing Dimensions (SCD) pada tabel dimensi.", "1", "C4"),
 ("2.1", "Membangun pipeline Extract-Transform-Load (ETL) otomatis menggunakan Airflow/Pentaho.", "2", "C6"),
 ("2.2", "Menerapkan proses data cleaning yang valid pada pipeline ETL.", "2", "C6"),
 ("3.1", "Mengimplementasikan operasi OLAP dan kueri analitik menggunakan SQL Window Functions.", "3", "C3"),
 ("3.2", "Menganalisis data faktual dan dimensional pada kubus data OLAP.", "3", "C3"),
 ("4.1", "Membangun dashboard Business Intelligence eksekutif interaktif menggunakan Power BI/Tableau.", "4", "C6"),
 ("4.2", "Merancang visualisasi KPI yang komunikatif untuk pengambilan keputusan.", "4", "C6"),
],
"STI-416": [
 ("1.1", "Membangun RESTful API modular menggunakan Node.js/Express atau Python FastAPI.", "1", "C3"),
 ("1.2", "Menerapkan penanganan rute, middleware, dan sanitasi input pada layanan backend.", "1", "C3"),
 ("2.1", "Mengintegrasikan backend dengan database relasional/NoSQL menggunakan ORM/ODM.", "2", "C3"),
 ("2.2", "Mengimplementasikan operasi CRUD transaksional dan query optimization.", "2", "C3"),
 ("3.1", "Mengimplementasikan autentikasi dan otorisasi JWT plus RBAC dengan enkripsi Bcrypt.", "3", "C4"),
 ("3.2", "Menerapkan session dan caching dasar (Redis) pada layanan backend.", "3", "C4"),
 ("4.1", "Mendokumentasikan API menggunakan Swagger/OpenAPI.", "4", "C6"),
 ("4.2", "Mendeploy backend ke server cloud menggunakan kontainer Docker.", "4", "C6"),
],
"STI-417": [
 ("1.1", "Membandingkan model layanan cloud (IaaS, PaaS, SaaS, FaaS) dan model deployment.", "1", "C4"),
 ("1.2", "Menganalisis peran virtualisasi dan hypervisor pada komputasi awan.", "1", "C4"),
 ("2.1", "Merancang dan mengemas aplikasi ke kontainer menggunakan Dockerfile dan Docker Compose.", "2", "C4"),
 ("2.2", "Mengoptimalkan layer caching pada pembangunan image kontainer.", "2", "C4"),
 ("3.1", "Mengonfigurasi provisioning VM dan object storage pada cloud provider (AWS/GCP).", "3", "C3"),
 ("3.2", "Mengonfigurasi Virtual Private Cloud (VPC) dan jaringan dasar cloud.", "3", "C3"),
 ("4.1", "Mengevaluasi arsitektur cloud dengan load balancing dan auto-scaling.", "4", "C5"),
 ("4.2", "Mengevaluasi toleransi bencana (high availability) pada sistem cloud.", "4", "C5"),
],
"STI-418": [
 ("1.1", "Menerapkan algoritma kriptografi simetris (AES) dan asimetris (RSA) pada proteksi data.", "1", "C3"),
 ("1.2", "Menerapkan fungsi hash (SHA-256) dan digital signature pada integritas data.", "1", "C3"),
 ("2.1", "Menganalisis kerentanan aplikasi web menggunakan metodologi OWASP Top 10.", "2", "C4"),
 ("2.2", "Menerapkan kontrol akses berbasis peran (RBAC) pada sistem informasi.", "2", "C4"),
 ("3.1", "Mengevaluasi insiden keamanan siber menggunakan kerangka NIST CSF.", "3", "C5"),
 ("3.2", "Mengevaluasi praktik keamanan informasi pada kerangka ISO/IEC 27001.", "3", "C5"),
],
"STI-519": [
 ("1.1", "Menganalisis tahapan penetration testing sesuai standar PTES dan MITRE ATT&CK.", "1", "C4"),
 ("1.2", "Mengonfigurasi vulnerability assessment menggunakan OpenVAS/Nessus.", "1", "C4"),
 ("2.1", "Mengidentifikasi kerentanan aplikasi web OWASP Top 10 menggunakan BurpSuite.", "2", "C4"),
 ("2.2", "Menganalisis binary dasar menggunakan reverse engineering (Ghidra).", "2", "C4"),
 ("3.1", "Mengevaluasi proses incident response pada insiden keamanan.", "3", "C5"),
 ("3.2", "Mengevaluasi kepatuhan terhadap kontrol audit ISO/IEC 27001.", "3", "C5"),
],
"STI-520": [
 ("1.1", "Menerapkan alur CRISP-DM dan exploratory data analysis pada dataset nyata.", "1", "C3"),
 ("1.2", "Mengimplementasikan visualisasi eksplorasi data menggunakan Seaborn dan Plotly.", "1", "C3"),
 ("2.1", "Mengimplementasikan association rule mining (Apriori dan FP-Growth).", "2", "C4"),
 ("2.2", "Menerapkan clustering lanjut (DBSCAN, Hierarchical) untuk segmentasi data.", "2", "C4"),
 ("3.1", "Mendeteksi outlier menggunakan Isolation Forest dan LOF.", "3", "C4"),
 ("3.2", "Menganalisis reduksi dimensi PCA dan t-SNE pada data berdimensi tinggi.", "3", "C4"),
 ("4.1", "Membangun dashboard visualisasi data interaktif untuk eksekutif.", "4", "C6"),
 ("4.2", "Menyusun laporan insight data berbasis visualisasi yang komunikatif.", "4", "C6"),
],
"STI-521": [
 ("1.1", "Membuat program perangkat IoT menggunakan pemrograman ESP32.", "1", "C3"),
 ("1.2", "Mengintegrasikan sensor analog/digital dan aktuator pada perangkat IoT.", "1", "C3"),
 ("2.1", "Mengimplementasikan komunikasi MQTT (Mosquitto) antara perangkat dan broker.", "2", "C3"),
 ("2.2", "Merancang alur data IoT menggunakan Node-RED.", "2", "C3"),
 ("3.1", "Mengintegrasikan perangkat IoT dengan dashboard cloud (ThingsBoard/Blynk).", "3", "C4"),
 ("3.2", "Merancang penyimpanan data time-series untuk aplikasi IoT.", "3", "C4"),
 ("4.1", "Membangun aplikasi IoT end-to-end dari sensor hingga dashboard analitik.", "4", "C6"),
 ("4.2", "Mengevaluasi performa dan keandalan sistem IoT yang dibangun.", "4", "C6"),
],
"STI-522": [
 ("1.1", "Membangun aplikasi mobile cross-platform menggunakan Flutter/Dart.", "1", "C3"),
 ("1.2", "Menerapkan konsep lifecycle dan UI widget pada pengembangan antarmuka mobile.", "1", "C3"),
 ("2.1", "Mengimplementasikan akses sensor perangkat (GPS, kamera, push notification).", "2", "C4"),
 ("2.2", "Menerapkan penyimpanan lokal SQLite/Hive pada aplikasi mobile.", "2", "C4"),
 ("3.1", "Mengintegrasikan aplikasi mobile dengan REST API untuk sinkronisasi offline-to-online.", "3", "C4"),
 ("3.2", "Mengelola state aplikasi mobile secara konsisten.", "3", "C4"),
 ("4.1", "Menguji dan merilis aplikasi mobile pada perangkat nyata.", "4", "C6"),
 ("4.2", "Membangun aplikasi mobile end-to-end yang terintegrasi dan siap rilis.", "4", "C6"),
],
"STI-523": [
 ("1.1", "Menyusun Project Charter dan Work Breakdown Structure (WBS) proyek TI.", "1", "C4"),
 ("1.2", "Mengestimasi upaya dan durasi proyek menggunakan COCOMO II dan PERT.", "1", "C4"),
 ("2.1", "Menyusun jadwal proyek menggunakan CPM dan Gantt chart.", "2", "C4"),
 ("2.2", "Menganalisis lintasan kritis dan slack pada jadwal proyek.", "2", "C4"),
 ("3.1", "Menerapkan praktik agile Scrum (sprint, daily, review, retrospective) pada proyek.", "3", "C3"),
 ("3.2", "Menggunakan Jira untuk pengelolaan backlog dan sprint.", "3", "C3"),
 ("4.1", "Melakukan manajemen risiko proyek dan menyusun rencana mitigasi.", "4", "C5"),
 ("4.2", "Mengevaluasi kinerja proyek menggunakan Earned Value Management (CPI, SPI, EAC).", "4", "C5"),
],
}
